### ISSUE TITLE
Which T5 model was used for fine-tuning?

### ISSUE THREAD

**Issue by Joapfel** [PrithivirajDamodaran/Parrot#11]
Hi, 
could you kindly tell which T5 model (T5-small, T5-base, T5-large, T5-3B, ....) the Parrot Project is based on? 

Kind regards

**Comment by TiloMichel** [comment]
It seems to be the T5-base model because the model from Parrot has the same size (pytorch-model.bin 850 MB) as the T5-base model.

Sources:
Parrot Model: https://huggingface.co/prithivida/parrot_paraphraser_on_T5/tree/main
T5-base: https://huggingface.co/t5-base/tree/main
