### ISSUE TITLE
401 Client Error  when using package

### ISSUE THREAD

**Issue by abbyDC** [PrithivirajDamodaran/Parrot#14]
I was able to use the package smoothly before but now it show 401 client error. How do i resolve this?
![error_parrot](https://user-images.githubusercontent.com/15419597/170973486-f908e435-0797-4abd-8569-08b490a83e2f.png)

**Comment by PrithivirajDamodaran** [comment]
reinstall the parrot package again.

**Comment by abbyDC** [comment]
> reinstall the parrot package again.

will do this thanks!
