### ISSUE TITLE
error: legacy-install-failure

### ISSUE THREAD

**Issue by hiddenchamp** [PrithivirajDamodaran/Parrot#16]
When trying to install I get this:

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-Levenshtein

How can I fix it?

**Comment by PrithivirajDamodaran** [comment]
I just tried installing and using the library, it installs and works fine.

**Comment by hiddenchamp** [comment]
Any idea how I can fix the issue? I am really new to python. I just installed it for the first time 3 days ago but parrot paraphraser is exactly what I need. I tried googling this error but I did not find the answer.
