### ISSUE TITLE
Installation Issue on Ubuntu

### ISSUE THREAD

**Issue by Bilal-irfan** [PrithivirajDamodaran/Parrot#25]
I am trying to install the library on Ubuntu but its not allowing me to install

**Comment by PrithivirajDamodaran** [comment]
Screenshot the issue.

**Comment by Bilal-irfan** [comment]
![image](https://user-images.githubusercontent.com/102790957/177531681-c8076d8e-f0f0-4f14-8508-68a8d8e272dd.png)
@PrithivirajDamodaran  can you please check 
I am running this **pip install git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git**

**Comment by Temur87** [comment]
I am having the exact same error with Windows (PyCharm - Python Version : 3.9.6)

**Comment by PrithivirajDamodaran** [comment]
I neither have a windows machine nor have a specific Ubuntu machine to test this.

**Comment by Temur87** [comment]
Which IDE do you recommend for Mac in this case ?

**Comment by PrithivirajDamodaran** [comment]
For the Ubuntu user this might be relevant - https://stackoverflow.com/questions/32595050/sudo-pip-install-python-levenshtein-failed-with-error-code-1?answertab=trending#tab-top


Please google, I am sure others have faced issues with levenshtien.

**Comment by smyja** [comment]
> ![image](https://user-images.githubusercontent.com/102790957/177531681-c8076d8e-f0f0-4f14-8508-68a8d8e272dd.png) @PrithivirajDamodaran can you please check I am running this **pip install git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git**

https://stackoverflow.com/a/61481091/6499765

**Comment by PrithivirajDamodaran** [comment]
I added a new demo notebook, and everything works fine. (check for the link in Readme)
