### ISSUE TITLE
Parrot returns very similar description without paraphrasing for some sentences

### ISSUE THREAD

**Issue by ElisonSherton** [PrithivirajDamodaran/Parrot#4]
Hi Prithviraj,

Good Day!

Awesome work on building this library! I tried to use it for a personal project from the fashion domain and here's what I observed:

![image](https://user-images.githubusercontent.com/45599762/119451617-1eb44d00-bd53-11eb-8fe4-8fd602853ebd.png)

![image](https://user-images.githubusercontent.com/45599762/119451759-41defc80-bd53-11eb-9f8c-c7fc8d43a39b.png)

Have a look at the two sentences above. I have provided the input sentence and the paraphrased sentence obtained using parrot. Except some punctuation and contractions, there's not much that the model is able to do.

Such is the case even for most of the descriptions that I have scraped through fashion retailers. Could you advise how can I use parrot to obtain better paraphrased suggestions please?

Thanks & Regards,
Vinayak Nayak.

**Comment by liuzzi** [comment]
i have also noticed this.

**Comment by PrithivirajDamodaran** [comment]
There is no universal model similarly there is no universal  paraphraser which will work across all text nuances from across domains. Performance and variety is a function of the data it has seen. 

For your needs and domain text feel free to fine tune your own paraphraser.
