### ISSUE TITLE
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by ChiragM-Hexaware** [PrithivirajDamodaran/Parrot#40]
Tried installing in kaggle - Parrot_Paraphraser. It got successfully installed but i tried using it in code it shows **ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.**

My internet connection is also ON on kaggle. Can you please check and tell. I have added screenshot too.
![image](https://user-images.githubusercontent.com/102511728/196092842-ab0e11a1-e03a-4be5-aa96-ec2516282f71.png)

**Comment by PrithivirajDamodaran** [comment]
I added a new demo notebook, and everything works fine. (check for the link in Readme)
