### ISSUE TITLE
Error: You need to have sentencepiece installed to convert a slow tokenizer to a fast one.

### ISSUE THREAD

**Issue by RahulBhasin** [PrithivirajDamodaran/Parrot#5]
Hi,

I am facing the error pasted below:
![Capture](https://user-images.githubusercontent.com/6624376/119705084-5b04ad80-be26-11eb-97e7-89274b801591.PNG)

I already have 'sentencepiece' installed. 
I also tried using 'use_fast=False' flag in parrot.py file (pasted below), as suggested in many other discussions for the resolution of this error. 
![Capture1](https://user-images.githubusercontent.com/6624376/119705701-10cffc00-be27-11eb-8f1a-69e3d90534fc.PNG)

However, I am still facing this issue. Can you please help me to resolve it?

Thanks,
Rahul

**Comment by PrithivirajDamodaran** [comment]
Not able to reproduce this issue.
