### ISSUE TITLE
Installation issue, torch >=1.6.0, Raspberry Pi OS 64 bit, Raspberry Pi 4b 8 gig

### ISSUE THREAD

**Issue by DaveXanatos** [PrithivirajDamodaran/Parrot#6]
Would love to get this working.  Getting two errors - first error here is the last thing the install reports before exiting back to the terminal prompt:

`Collecting torch>=1.6.0 (from sentence-transformers->parrot==1.0)
  Could not find a version that satisfies the requirement torch>=1.6.0 (from sentence-transformers->parrot==1.0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch>=1.6.0 (from sentence-transformers->parrot==1.0)`

Tried running the quick start script anyway, get this error:

`Traceback (most recent call last):
  File "paraphrase.py", line 1, in <module>
    from parrot import Parrot
ModuleNotFoundError: No module named 'parrot'`

Raspberry Pi 4B 8 Gig RAM version, running Raspberry Pi OS 64 Bit.
Apologies if I have not provided sufficient info here - let me know how else I may help to figure out why this won't run on my build.  Thanks

**Comment by PrithivirajDamodaran** [comment]
Not able to reproduce this issue

**Comment by DaveXanatos** [comment]
Were you using the 64-bit OS?  I suspect some of the issue is coming from some of the requirements being 32-bit only and pip is looking for them under arm64 and not finding them....  I'm going to try some of the failed parts of the install and specify :armhf to see if that works.  Because it does NOT on a fresh install of the latest R Pi 64-bit OS.
